### ISSUE TITLE
Bootstrap process doesn't install pip but calls pip

### ISSUE THREAD

**Issue by jfunction** [kernsuite/singularity#2]
I received the following error while bootstrapping:

```
...
done.
done.
+ apt-get clean
+ pip install --upgrade pip virtualenv
/bin/sh: 9: pip: not found
ERROR: Aborting with RETVAL=255
Makefile:11: recipe for target 'bootstrap' failed
make: *** [bootstrap] Error 255
```

I added the `python-pip` package to the Singularity file and the issue was fixed for me.

https://github.com/kernsuite/singularity/blob/b64089fc86a142740383c716b377e7ead698659c/Singularity#L12

**Comment by gijzelaerr** [comment]
fixed for all branches.
