### ISSUE TITLE
pip gets broken(?) by ```pip install --upgrade pip virtualenv```

### ISSUE THREAD

**Issue by vdmz** [kernsuite/singularity#3]
Thanks for this helpful little repo, btw.
I was trying to build a kern-3 image because some things I need are not yet in kern-4.
I wanted to add a further pip package, so I appended this line to the Singularity file
```
pip install astLib
```
and was rewarded with (at the end of a lengthy image build)
```
+ pip install astLib
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip import main
ImportError: cannot import name main
ABORT: Aborting with RETVAL=255
Cleaning up...
```
Why this is needed in the Singularity file?
```
pip install --upgrade pip virtualenv
```

Discussion of this issue here suggests it's not good practice:
 * https://github.com/pypa/pip/issues/5221
 * https://github.com/pypa/pip/issues/5346
 * https://github.com/pypa/pip/issues/5599

I was able to add the extra module with
```
python -m pip install astLib
```

**Comment by gijzelaerr** [comment]
What is missing in KERN-4 exactly? You can make an issue for that if you want.

Thanks for reporting, i'll remove the installation of pip, then the user can decide what needs to happen.

**Comment by gijzelaerr** [comment]
btw it is a path issue, `/usr/local/bin` should be looked at before `/usr/bin`, but somehow that doesn't happen inside the container. If you do `/usr/local/bin/pip install etc` it works.
